module "canadacentral" {
    source          = "./cac"
    region          = "canadacentral"
    region_code     = "cac"
    vnet-name       = "network"
    hub-name        = "hub"
    soke-name       = "spoke"
    vnet-cidr       = "10.0.0.0/16"
    nsg-name        = "nsg"
    snet-1-name     = "one"
    snet1-cidr      = "10.0.1.0/24"
    snet-2-name     = "two"
    snet2-cidr      = "10.0.2.0/24"
    snet-3-name     = "three"
    snet3-cidr      = "10.0.3.0/24"
    snet-4-name     = "PrivateEndpoint"
    snet4-cidr      = "10.0.4.0/24"
    udr1-name       = "one"
    nsg1-name       = "one"
}

# module "canadaeast" {
#     source          = "./cae"
#     region          = "canadaeast"
#     region_code     = "cae"
#     vnet-name       = "network"
#     network-name    = "one"
#     vnet-cidr       = "10.1.0.0/16"
#     nsg-name        = "nsg"
#     snet-1-name     = "one"
#     snet1-cidr      = "10.1.1.0/24"
#     snet-2-name     = "two"
#     snet2-cidr      = "10.1.2.0/24"
#     snet-3-name     = "three"
#     snet3-cidr      = "10.1.3.0/24"
#     snet-4-name     = "PrivateEndpoint"
#     snet4-cidr      = "10.1.4.0/24"
#     udr1-name       = "one"
#     nsg1-name       = "one"
# }